#import "DollarDefaultGestures.h"
#import "DollarPointCloud.h"
#import "DollarPoint.h"

DollarPointCloud * MakePointCloud(NSString *name, NSArray *points) {
    return [[DollarPointCloud alloc] initWithName:name points:points];
}

DollarPoint * MakePoint(float x, float y, int id) {
    return [[DollarPoint alloc] initWithId:@(id) x:x y:y];
}

@implementation DollarDefaultGestures

+ (id)defaultPointClouds {
    static NSArray *defaultPointClouds = nil;
    if (!defaultPointClouds) {
        defaultPointClouds = [self pointClouds];
    }
    return defaultPointClouds;
}
//{T,F,D,P,G,C,B,A,S,Heart(Symbol),Camera(Symbol),Flash,Video,Square,timer,grids,settings,add(plus),share,delete}
+ (NSMutableArray *)pointClouds {
    NSMutableArray *pointClouds = [NSMutableArray array];
   	pointClouds[0] = MakePointCloud(@"T", @[
                                            MakePoint(30,7,1),
                                            MakePoint(103,7,1),
                                            
                                            MakePoint(66,7,2),
                                            MakePoint(66,87,2)
                                            ]);
    
    pointClouds[1] = MakePointCloud(@"F", @[
                                            MakePoint(528 ,178,1),
                                            MakePoint(519 ,178,1),
                                            MakePoint(497 ,178,1),
                                            MakePoint(471 ,178,1),
                                            MakePoint(441 ,178,1),
                                            MakePoint(401 ,179,1),
                                            MakePoint(364 ,180,1),
                                            MakePoint(329 ,181,1),
                                            MakePoint(296 ,184,1),
                                            MakePoint(270 ,187,1),
                                            MakePoint(245 ,191,1),
                                            MakePoint(224 ,196,1),
                                            MakePoint(208 ,200,1),
                                            MakePoint(195 ,205,1),
                                            MakePoint(186 ,210,1),
                                            MakePoint(179 ,216,1),
                                            MakePoint(175 ,225,1),
                                            MakePoint(172 ,235,1),
                                            MakePoint(171 ,251,1),
                                            MakePoint(171 ,274,1),
                                            MakePoint(171 ,299,1),
                                            MakePoint(172 ,335,1),
                                            MakePoint(172 ,374,1),
                                            MakePoint(173 ,416,1),
                                            MakePoint(175 ,462,1),
                                            MakePoint(176 ,512,1),
                                            MakePoint(177 ,560,1),
                                            MakePoint(178 ,608,1),
                                            MakePoint(179 ,654,1),
                                            MakePoint(180 ,693,1),
                                            MakePoint(180 ,721,1),
                                            MakePoint(181 ,746,1),
                                            MakePoint(181 ,761,1),
                                            MakePoint(182 ,772,1),
                                            MakePoint(182 ,777,1),
                                            MakePoint(183 ,781,1),
                                            MakePoint(171 ,473,2),
                                            MakePoint(181 ,473,2),
                                            MakePoint(199 ,473,2),
                                            MakePoint(227 ,473,2),
                                            MakePoint(265 ,473,2),
                                            MakePoint(303 ,473,2),
                                            MakePoint(344 ,473,2),
                                            MakePoint(383 ,472,2),
                                            MakePoint(420 ,471,2),
                                            MakePoint(448 ,470,2),
                                            MakePoint(472 ,469,2),
                                            MakePoint(486 ,468,2),
                                            MakePoint(493 ,467,2),
                                            MakePoint(496 ,467,2),
                                            MakePoint(497 ,467,2),
                                            MakePoint(492 ,467,2) ]);
    
    
    
    pointClouds[2] = MakePointCloud(@"D", @[
                                            MakePoint(102 ,163,1),
                                            MakePoint(102 ,168,1),
                                            MakePoint(102 ,176,1),
                                            MakePoint(102 ,188,1),
                                            MakePoint(102 ,203,1),
                                            MakePoint(100 ,219,1),
                                            MakePoint(100 ,237,1),
                                            MakePoint(100 ,256,1),
                                            MakePoint(100 ,274,1),
                                            MakePoint(100 ,291,1),
                                            MakePoint(100 ,308,1),
                                            MakePoint(102 ,324,1),
                                            MakePoint(103 ,339,1),
                                            MakePoint(104 ,352,1),
                                            MakePoint(105 ,364,1),
                                            MakePoint(105 ,373,1),
                                            MakePoint(105 ,382,1),
                                            MakePoint(105 ,389,1),
                                            MakePoint(105 ,393,1),
                                            MakePoint(105 ,396,1),
                                            MakePoint(105 ,396,1),
                                            MakePoint(37 ,179,2),
                                            MakePoint(40 ,179,2),
                                            MakePoint(47 ,176,2),
                                            MakePoint(53 ,174,2),
                                            MakePoint(60 ,171,2),
                                            MakePoint(69 ,168,2),
                                            MakePoint(76 ,166,2),
                                            MakePoint(84 ,164,2),
                                            MakePoint(90 ,162,2),
                                            MakePoint(97 ,161,2),
                                            MakePoint(104 ,160,2),
                                            MakePoint(110 ,160,2),
                                            MakePoint(117 ,159,2),
                                            MakePoint(123 ,159,2),
                                            MakePoint(128 ,159,2),
                                            MakePoint(134 ,159,2),
                                            MakePoint(139 ,159,2),
                                            MakePoint(145 ,159,2),
                                            MakePoint(150 ,159,2),
                                            MakePoint(155 ,160,2),
                                            MakePoint(159 ,161,2),
                                            MakePoint(163 ,163,2),
                                            MakePoint(168 ,164,2),
                                            MakePoint(173 ,167,2),
                                            MakePoint(178 ,169,2),
                                            MakePoint(183 ,171,2),
                                            MakePoint(188 ,173,2),
                                            MakePoint(192 ,175,2),
                                            MakePoint(198 ,178,2),
                                            MakePoint(203 ,181,2),
                                            MakePoint(209 ,184,2),
                                            MakePoint(215 ,187,2),
                                            MakePoint(221 ,190,2),
                                            MakePoint(225 ,193,2),
                                            MakePoint(231 ,197,2),
                                            MakePoint(236 ,200,2),
                                            MakePoint(242 ,204,2),
                                            MakePoint(247 ,208,2),
                                            MakePoint(252 ,211,2),
                                            MakePoint(257 ,215,2),
                                            MakePoint(261 ,220,2),
                                            MakePoint(264 ,224,2),
                                            MakePoint(267 ,230,2),
                                            MakePoint(271 ,235,2),
                                            MakePoint(275 ,240,2),
                                            MakePoint(279 ,245,2),
                                            MakePoint(282 ,251,2),
                                            MakePoint(286 ,257,2),
                                            MakePoint(289 ,263,2),
                                            MakePoint(291 ,269,2),
                                            MakePoint(293 ,276,2),
                                            MakePoint(293 ,282,2),
                                            MakePoint(294 ,289,2),
                                            MakePoint(294 ,296,2),
                                            MakePoint(294 ,304,2),
                                            MakePoint(293 ,311,2),
                                            MakePoint(291 ,318,2),
                                            MakePoint(288 ,324,2),
                                            MakePoint(285 ,330,2),
                                            MakePoint(282 ,335,2),
                                            MakePoint(279 ,340,2),
                                            MakePoint(276 ,346,2),
                                            MakePoint(274 ,351,2),
                                            MakePoint(271 ,355,2),
                                            MakePoint(267 ,360,2),
                                            MakePoint(264 ,365,2),
                                            MakePoint(261 ,369,2),
                                            MakePoint(258 ,372,2),
                                            MakePoint(255 ,375,2),
                                            MakePoint(250 ,378,2),
                                            MakePoint(246 ,381,2),
                                            MakePoint(242 ,383,2),
                                            MakePoint(237 ,384,2),
                                            MakePoint(232 ,386,2),
                                            MakePoint(227 ,387,2),
                                            MakePoint(221 ,389,2),
                                            MakePoint(216 ,390,2),
                                            MakePoint(209 ,391,2),
                                            MakePoint(203 ,392,2),
                                            MakePoint(196 ,394,2),
                                            MakePoint(189 ,395,2),
                                            MakePoint(182 ,396,2),
                                            MakePoint(174 ,398,2),
                                            MakePoint(167 ,399,2),
                                            MakePoint(161 ,400,2),
                                            MakePoint(155 ,401,2),
                                            MakePoint(148 ,402,2),
                                            MakePoint(141 ,403,2),
                                            MakePoint(135 ,403,2),
                                            MakePoint(129 ,404,2),
                                            MakePoint(122 ,404,2),
                                            MakePoint(116 ,404,2),
                                            MakePoint(108 ,404,2),
                                            MakePoint(102 ,404,2),
                                            MakePoint(97 ,404,2),
                                            MakePoint(92 ,404,2),
                                            MakePoint(87 ,402,2),
                                            MakePoint(83 ,401,2),
                                            MakePoint(78 ,400,2),
                                            MakePoint(74 ,398,2),
                                            MakePoint(71 ,396,2),
                                            MakePoint(67 ,395,2),
                                            MakePoint(63 ,393,2),
                                            MakePoint(60 ,391,2),
                                            MakePoint(56 ,389,2),
                                            MakePoint(52 ,387,2),
                                            MakePoint(49 ,386,2),
                                            MakePoint(45 ,384,2),
                                            MakePoint(42 ,383,2),
                                            MakePoint(40 ,382,2),
                                            MakePoint(38 ,380,2),
                                            MakePoint(37 ,379,2),
                                            MakePoint(36 ,378,2),
                                            MakePoint(35 ,378,2),
                                            MakePoint(35 ,377,2),
                                            MakePoint(35 ,377,2)
                                            ]);
    
    pointClouds[3] = MakePointCloud(@"P", @[
                                            MakePoint(507,8,1),
                                            MakePoint(507,87,1),
                                            
                                            MakePoint(513,7,2),
                                            MakePoint(528,7,2),
                                            MakePoint(537,8,2),
                                            MakePoint(544,10,2),
                                            MakePoint(550,12,2),
                                            MakePoint(555,15,2),
                                            MakePoint(558,18,2),
                                            MakePoint(560,22,2),
                                            MakePoint(561,27,2),
                                            MakePoint(562,33,2),
                                            MakePoint(561,37,2),
                                            MakePoint(559,42,2),
                                            MakePoint(556,45,2),
                                            MakePoint(550,48,2),
                                            MakePoint(544,51,2),
                                            MakePoint(538,53,2),
                                            MakePoint(532,54,2),
                                            MakePoint(525,55,2),
                                            MakePoint(519,55,2),
                                            MakePoint(513,55,2),
                                            MakePoint(510,55,2)
                                            ]);
    
    pointClouds[4] = MakePointCloud(@"G", @[
                                            MakePoint(158 ,177,1),
                                            MakePoint(156 ,177,1),
                                            MakePoint(152 ,177,1),
                                            MakePoint(142 ,177,1),
                                            MakePoint(131 ,177,1),
                                            MakePoint(125 ,177,1),
                                            MakePoint(115 ,177,1),
                                            MakePoint(104 ,177,1),
                                            MakePoint(95 ,179,1),
                                            MakePoint(90 ,179,1),
                                            MakePoint(79 ,181,1),
                                            MakePoint(71 ,182,1),
                                            MakePoint(61 ,185,1),
                                            MakePoint(57 ,188,1),
                                            MakePoint(55 ,193,1),
                                            MakePoint(53 ,202,1),
                                            MakePoint(51 ,230,1),
                                            MakePoint(51 ,246,1),
                                            MakePoint(51 ,260,1),
                                            MakePoint(51 ,274,1),
                                            MakePoint(52 ,286,1),
                                            MakePoint(53 ,307,1),
                                            MakePoint(55 ,314,1),
                                            MakePoint(59 ,324,1),
                                            MakePoint(66 ,337,1),
                                            MakePoint(76 ,347,1),
                                            MakePoint(90 ,353,1),
                                            MakePoint(102 ,358,1),
                                            MakePoint(114 ,360,1),
                                            MakePoint(129 ,362,1),
                                            MakePoint(139 ,362,1),
                                            MakePoint(148 ,362,1),
                                            MakePoint(155 ,362,1),
                                            MakePoint(161 ,362,1),
                                            MakePoint(166 ,362,1),
                                            MakePoint(170 ,358,1),
                                            MakePoint(171 ,355,1),
                                            MakePoint(172 ,351,1),
                                            MakePoint(172 ,342,1),
                                            MakePoint(172 ,330,1),
                                            MakePoint(172 ,316,1),
                                            MakePoint(173 ,308,1),
                                            MakePoint(173 ,300,1),
                                            MakePoint(173 ,290,1),
                                            MakePoint(173 ,287,1),
                                            MakePoint(173 ,280,1),
                                            MakePoint(173 ,277,1),
                                            MakePoint(173 ,275,1),
                                            MakePoint(172 ,274,1),
                                            MakePoint(172 ,273,1),
                                            MakePoint(171 ,272,1),
                                            MakePoint(170 ,271,1),
                                            MakePoint(169 ,270,1),
                                            MakePoint(168 ,268,1),
                                            MakePoint(167 ,267,1),
                                            MakePoint(166 ,266,1),
                                            MakePoint(165 ,264,1),
                                            MakePoint(164 ,262,1),
                                            MakePoint(162 ,261,1),
                                            MakePoint(156 ,259,1),
                                            MakePoint(152 ,259,1),
                                            MakePoint(146 ,258,1),
                                            MakePoint(145 ,258,1),
                                            MakePoint(144 ,258,1),
                                            MakePoint(143 ,258,1),
                                            MakePoint(142 ,258,1),
                                            MakePoint(142 ,259,1),
                                            MakePoint(144 ,259,1),
                                            MakePoint(147 ,259,1),
                                            MakePoint(163 ,259,1),
                                            MakePoint(173 ,259,1),
                                            MakePoint(179 ,259,1),
                                            MakePoint(182 ,260,1),
                                            MakePoint(183 ,260,1),
                                            MakePoint(183 ,261,1),
                                            MakePoint(183 ,263,1),
                                            MakePoint(183 ,268,1),
                                            MakePoint(182 ,276,1),
                                            MakePoint(182 ,283,1),
                                            MakePoint(181 ,295,1),
                                            MakePoint(181 ,306,1),
                                            MakePoint(180 ,320,1),
                                            MakePoint(180 ,328,1),
                                            MakePoint(180 ,332,1),
                                            MakePoint(180 ,335,1),
                                            MakePoint(180 ,336,1),
                                            MakePoint(180 ,337,1),
                                            MakePoint(179 ,337,1),
                                            MakePoint(179 ,338,1),
                                            MakePoint(179 ,339,1),
                                            MakePoint(179 ,340,1),
                                            MakePoint(179 ,344,1),
                                            MakePoint(179 ,347,1),
                                            MakePoint(179 ,351,1),
                                            MakePoint(179 ,352,1),
                                            MakePoint(179 ,353,1),
                                            MakePoint(179 ,355,1),
                                            MakePoint(179 ,356,1),
                                            MakePoint(179 ,357,1),
                                            MakePoint(179 ,358,1),
                                            MakePoint(179 ,359,1),
                                            MakePoint(179 ,360,1),
                                            MakePoint(179 ,362,1),
                                            MakePoint(179 ,363,1),
                                            MakePoint(179 ,364,1),
                                            MakePoint(179 ,365,1),
                                            MakePoint(179 ,366,1),
                                            MakePoint(179 ,367,1)
                                            
                                            ]);
    pointClouds[5] = MakePointCloud(@"C", @[
                                            MakePoint(224,162,1),
                                            MakePoint(222 ,159,1),
                                            MakePoint(211 ,157,1),
                                            MakePoint(198 ,155,1),
                                            MakePoint(173 ,154,1),
                                            MakePoint(131 ,154,1),
                                            MakePoint(118 ,157,1),
                                            MakePoint(108 ,168,1),
                                            MakePoint(95 ,199,1),
                                            MakePoint(87 ,219,1),
                                            MakePoint(84 ,253,1),
                                            MakePoint(84 ,269,1),
                                            MakePoint(84 ,286,1),
                                            MakePoint(85 ,310,1),
                                            MakePoint(87 ,320,1),
                                            MakePoint(91 ,330,1),
                                            MakePoint(95 ,339,1),
                                            MakePoint(98 ,343,1),
                                            MakePoint(106 ,350,1),
                                            MakePoint(121 ,362,1),
                                            MakePoint(130 ,367,1),
                                            MakePoint(141 ,371,1),
                                            MakePoint(150 ,372,1),
                                            MakePoint(159 ,372,1),
                                            MakePoint(170 ,372,1),
                                            MakePoint(183 ,372,1),
                                            MakePoint(192 ,372,1),
                                            MakePoint(195 ,372,1),
                                            MakePoint(196 ,371,1),
                                            MakePoint(199 ,371,1),
                                            MakePoint(200 ,370,1),
                                            MakePoint(201 ,370,1),
                                            MakePoint(201 ,369,1),
                                            MakePoint(203 ,369,1),
                                            MakePoint(204 ,369,1),
                                            MakePoint(205 ,368,1),
                                            MakePoint(207 ,367,1),
                                            MakePoint(213 ,367,1),
                                            MakePoint(216 ,367,1),
                                            MakePoint(218 ,367,1),
                                            MakePoint(219 ,367,1),
                                            MakePoint(221 ,367,1),
                                            MakePoint(221 ,365,1),
                                            MakePoint(222 ,365,1)
                                            ]);
    
    //	pointClouds[5] = MakePointCloud(@"H", @[
    //                                    MakePoint(188,137,1),
    //                                    MakePoint(188,225,1),
    //
    //                                    MakePoint(188,180,2),
    //                                    MakePoint(241,180,2),
    //
    //                                    MakePoint(241,137,3),
    //                                    MakePoint(241,225,3)
    //                                    ]);
    
    pointClouds[6] = MakePointCloud(@"B", @[
                                            MakePoint(94 ,171,1),
                                            MakePoint(94 ,176,1),
                                            MakePoint(94 ,191,1),
                                            MakePoint(94 ,217,1),
                                            MakePoint(94 ,243,1),
                                            MakePoint(94 ,269,1),
                                            MakePoint(94 ,293,1),
                                            MakePoint(94 ,310,1),
                                            MakePoint(94 ,320,1),
                                            MakePoint(94 ,327,1),
                                            MakePoint(94 ,346,1),
                                            MakePoint(94 ,352,1),
                                            MakePoint(94 ,359,1),
                                            MakePoint(94 ,366,1),
                                            MakePoint(94 ,367,1),
                                            MakePoint(94 ,369,1),
                                            MakePoint(94 ,370,1),
                                            MakePoint(94 ,371,1),
                                            MakePoint(94 ,374,1),
                                            MakePoint(94 ,375,1),
                                            MakePoint(94 ,376,1),
                                            MakePoint(94 ,378,1),
                                            MakePoint(94 ,380,1),
                                            MakePoint(95 ,381,1),
                                            MakePoint(95 ,382,1),
                                            MakePoint(104 ,164,2),
                                            MakePoint(108 ,164,2),
                                            MakePoint(129 ,164,2),
                                            MakePoint(141 ,165,2),
                                            MakePoint(151 ,166,2),
                                            MakePoint(157 ,169,2),
                                            MakePoint(162 ,176,2),
                                            MakePoint(164 ,180,2),
                                            MakePoint(166 ,186,2),
                                            MakePoint(167 ,190,2),
                                            MakePoint(168 ,196,2),
                                            MakePoint(169 ,203,2),
                                            MakePoint(169 ,209,2),
                                            MakePoint(169 ,215,2),
                                            MakePoint(169 ,222,2),
                                            MakePoint(169 ,226,2),
                                            MakePoint(168 ,229,2),
                                            MakePoint(167 ,234,2),
                                            MakePoint(163 ,242,2),
                                            MakePoint(155 ,249,2),
                                            MakePoint(147 ,256,2),
                                            MakePoint(142 ,262,2),
                                            MakePoint(136 ,266,2),
                                            MakePoint(132 ,269,2),
                                            MakePoint(130 ,271,2),
                                            MakePoint(128 ,272,2),
                                            MakePoint(125 ,273,2),
                                            MakePoint(122 ,275,2),
                                            MakePoint(119 ,276,2),
                                            MakePoint(114 ,278,2),
                                            MakePoint(112 ,279,2),
                                            MakePoint(110 ,279,2),
                                            MakePoint(110 ,280,2),
                                            MakePoint(109 ,280,2),
                                            MakePoint(108 ,281,2),
                                            MakePoint(107 ,282,2),
                                            MakePoint(106 ,282,2),
                                            MakePoint(106 ,282,2),
                                            MakePoint(105 ,282,2),
                                            MakePoint(104 ,282,2),
                                            MakePoint(104 ,283,2),
                                            MakePoint(103 ,283,2),
                                            MakePoint(102 ,283,2),
                                            MakePoint(102 ,284,2),
                                            MakePoint(101 ,284,2),
                                            MakePoint(100 ,284,2),
                                            MakePoint(98 ,285,2),
                                            MakePoint(97 ,285,2),
                                            MakePoint(96 ,286,2),
                                            MakePoint(95 ,286,2),
                                            MakePoint(99 ,286,2),
                                            MakePoint(108 ,286,2),
                                            MakePoint(122 ,286,2),
                                            MakePoint(140 ,286,2),
                                            MakePoint(155 ,288,2),
                                            MakePoint(166 ,289,2),
                                            MakePoint(171 ,295,2),
                                            MakePoint(174 ,306,2),
                                            MakePoint(181 ,327,2),
                                            MakePoint(182 ,340,2),
                                            MakePoint(183 ,354,2),
                                            MakePoint(184 ,363,2),
                                            MakePoint(184 ,370,2),
                                            MakePoint(183 ,373,2),
                                            MakePoint(182 ,375,2),
                                            MakePoint(180 ,377,2),
                                            MakePoint(177 ,380,2),
                                            MakePoint(174 ,382,2),
                                            MakePoint(171 ,384,2),
                                            MakePoint(167 ,389,2),
                                            MakePoint(163 ,391,2),
                                            MakePoint(159 ,392,2),
                                            MakePoint(153 ,393,2),
                                            MakePoint(147 ,393,2),
                                            MakePoint(144 ,394,2),
                                            MakePoint(136 ,395,2),
                                            MakePoint(134 ,396,2),
                                            MakePoint(129 ,396,2),
                                            MakePoint(128 ,396,2),
                                            MakePoint(126 ,396,2),
                                            MakePoint(125 ,396,2),
                                            MakePoint(124 ,396,2),
                                            MakePoint(123 ,396,2),
                                            MakePoint(121 ,396,2),
                                            MakePoint(120 ,396,2),
                                            MakePoint(115 ,396,2),
                                            MakePoint(111 ,396,2),
                                            MakePoint(108 ,396,2),
                                            MakePoint(106 ,396,2),
                                            MakePoint(105 ,396,2),
                                            MakePoint(105 ,396,2),
                                            MakePoint(105 ,394,2),
                                            MakePoint(104 ,394,2),
                                            MakePoint(104 ,394,2),
                                            MakePoint(103 ,394,2),
                                            MakePoint(102 ,391,2),
                                            MakePoint(94 ,388,2),
                                            MakePoint(92 ,386,2),
                                            MakePoint(91 ,386,2)
                                            ]);
    pointClouds[7] = MakePointCloud(@"A", @[
                                            MakePoint(62 ,412,1),
                                            MakePoint(62 ,405,1),
                                            MakePoint(64 ,396,1),
                                            MakePoint(67 ,384,1),
                                            MakePoint(71 ,371,1),
                                            MakePoint(75 ,359,1),
                                            MakePoint(80 ,345,1),
                                            MakePoint(84 ,331,1),
                                            MakePoint(88 ,316,1),
                                            MakePoint(92 ,299,1),
                                            MakePoint(95 ,282,1),
                                            MakePoint(98 ,264,1),
                                            MakePoint(102 ,247,1),
                                            MakePoint(106 ,230,1),
                                            MakePoint(110 ,214,1),
                                            MakePoint(115 ,198,1),
                                            MakePoint(119 ,183,1),
                                            MakePoint(123 ,170,1),
                                            MakePoint(125 ,161,1),
                                            MakePoint(128 ,151,1),
                                            MakePoint(130 ,143,1),
                                            MakePoint(132 ,137,1),
                                            MakePoint(135 ,128,1),
                                            MakePoint(136 ,126,1),
                                            MakePoint(136 ,123,1),
                                            MakePoint(137 ,122,1),
                                            MakePoint(137 ,122,1),
                                            MakePoint(138 ,122,1),
                                            MakePoint(139 ,122,1),
                                            MakePoint(141 ,125,1),
                                            MakePoint(145 ,130,1),
                                            MakePoint(149 ,137,1),
                                            MakePoint(154 ,146,1),
                                            MakePoint(159 ,156,1),
                                            MakePoint(165 ,168,1),
                                            MakePoint(171 ,180,1),
                                            MakePoint(177 ,190,1),
                                            MakePoint(182 ,203,1),
                                            MakePoint(187 ,215,1),
                                            MakePoint(191 ,227,1),
                                            MakePoint(196 ,241,1),
                                            MakePoint(201 ,253,1),
                                            MakePoint(205 ,265,1),
                                            MakePoint(210 ,276,1),
                                            MakePoint(214 ,287,1),
                                            MakePoint(217 ,297,1),
                                            MakePoint(220 ,308,1),
                                            MakePoint(222 ,319,1),
                                            MakePoint(224 ,330,1),
                                            MakePoint(226 ,340,1),
                                            MakePoint(228 ,351,1),
                                            MakePoint(230 ,360,1),
                                            MakePoint(231 ,368,1),
                                            MakePoint(233 ,377,1),
                                            MakePoint(235 ,385,1),
                                            MakePoint(236 ,393,1),
                                            MakePoint(237 ,399,1),
                                            MakePoint(238 ,405,1),
                                            MakePoint(239 ,410,1),
                                            MakePoint(240 ,414,1),
                                            MakePoint(240 ,418,1),
                                            MakePoint(241 ,421,1),
                                            MakePoint(242 ,424,1),
                                            MakePoint(242 ,427,1),
                                            MakePoint(243 ,428,1),
                                            MakePoint(244 ,430,1),
                                            MakePoint(244 ,431,1),
                                            MakePoint(245 ,432,1),
                                            MakePoint(245 ,432,1),
                                            MakePoint(245 ,433,1),
                                            MakePoint(245 ,434,1),
                                            MakePoint(246 ,434,1),
                                            MakePoint(96 ,280,2),
                                            MakePoint(101 ,278,2),
                                            MakePoint(109 ,276,2),
                                            MakePoint(118 ,274,2),
                                            MakePoint(128 ,272,2),
                                            MakePoint(142 ,270,2),
                                            MakePoint(153 ,267,2),
                                            MakePoint(166 ,264,2),
                                            MakePoint(178 ,262,2),
                                            MakePoint(186 ,259,2),
                                            MakePoint(193 ,258,2),
                                            MakePoint(199 ,256,2),
                                            MakePoint(204 ,255,2),
                                            MakePoint(207 ,255,2),
                                            MakePoint(209 ,255,2),
                                            MakePoint(210 ,255,2),
                                            MakePoint(212 ,255,2),
                                            MakePoint(212 ,255,2),
                                            MakePoint(213 ,255,2),
                                            MakePoint(213 ,255,2),
                                            MakePoint(214 ,255,2),
                                            MakePoint(215 ,255,2),
                                            MakePoint(216 ,255,2),
                                            MakePoint(216 ,255,2),
                                            MakePoint(217 ,255,2),
                                            MakePoint(217 ,255,2),
                                            MakePoint(218 ,255,2),
                                            MakePoint(220 ,255,2),
                                            MakePoint(221 ,255,2),
                                            MakePoint(223 ,254,2),
                                            MakePoint(224 ,254,2),
                                            MakePoint(225 ,254,2),
                                            MakePoint(226 ,254,2),
                                            MakePoint(226 ,254,2),
                                            MakePoint(227 ,254,2),
                                            MakePoint(228 ,254,2),
                                            MakePoint(229 ,254,2),
                                            MakePoint(230 ,254,2),
                                            MakePoint(231 ,254,2),
                                            MakePoint(231 ,254,2),
                                            MakePoint(232 ,254,2),
                                            MakePoint(232 ,254,2),
                                            ]
                                    );
    
    pointClouds[8] = MakePointCloud(@"S", @[
                                            MakePoint(249 ,146,1),
                                            MakePoint(245 ,145,1),
                                            MakePoint(240 ,143,1),
                                            MakePoint(232 ,141,1),
                                            MakePoint(223 ,138,1),
                                            MakePoint(213 ,135,1),
                                            MakePoint(200 ,133,1),
                                            MakePoint(188 ,133,1),
                                            MakePoint(171 ,133,1),
                                            MakePoint(156 ,133,1),
                                            MakePoint(138 ,140,1),
                                            MakePoint(125 ,146,1),
                                            MakePoint(110 ,154,1),
                                            MakePoint(99 ,163,1),
                                            MakePoint(92 ,170,1),
                                            MakePoint(87 ,179,1),
                                            MakePoint(83 ,186,1),
                                            MakePoint(82 ,194,1),
                                            MakePoint(82 ,202,1),
                                            MakePoint(84 ,210,1),
                                            MakePoint(90 ,217,1),
                                            MakePoint(100 ,224,1),
                                            MakePoint(112 ,230,1),
                                            MakePoint(124 ,237,1),
                                            MakePoint(140 ,243,1),
                                            MakePoint(156 ,248,1),
                                            MakePoint(173 ,255,1),
                                            MakePoint(187 ,260,1),
                                            MakePoint(201 ,266,1),
                                            MakePoint(214 ,272,1),
                                            MakePoint(226 ,279,1),
                                            MakePoint(239 ,286,1),
                                            MakePoint(249 ,294,1),
                                            MakePoint(256 ,302,1),
                                            MakePoint(263 ,311,1),
                                            MakePoint(268 ,321,1),
                                            MakePoint(271 ,331,1),
                                            MakePoint(273 ,341,1),
                                            MakePoint(273 ,352,1),
                                            MakePoint(273 ,362,1),
                                            MakePoint(267 ,374,1),
                                            MakePoint(260 ,385,1),
                                            MakePoint(249 ,395,1),
                                            MakePoint(234 ,406,1),
                                            MakePoint(219 ,414,1),
                                            MakePoint(204 ,418,1),
                                            MakePoint(188 ,421,1),
                                            MakePoint(171 ,421,1),
                                            MakePoint(156 ,421,1),
                                            MakePoint(144 ,418,1),
                                            MakePoint(133 ,412,1),
                                            MakePoint(127 ,405,1),
                                            MakePoint(121 ,398,1),
                                            MakePoint(117 ,390,1),
                                            MakePoint(113 ,382,1),
                                            MakePoint(109 ,374,1),
                                            MakePoint(106 ,368,1),
                                            MakePoint(103 ,362,1),
                                            MakePoint(100 ,356,1),
                                            MakePoint(97 ,351,1),
                                            MakePoint(95 ,346,1),
                                            MakePoint(92 ,343,1),
                                            MakePoint(89 ,340,1),
                                            MakePoint(88 ,338,1),
                                            MakePoint(86 ,336,1),
                                            MakePoint(86 ,335,1)
                                            
                                            
                                            
                                            
                                            ]);
    
    	pointClouds[9] = MakePointCloud(@"V", @[
                                                 MakePoint(175 ,296,1),
                                                 MakePoint(175 ,299,1),
                                                 MakePoint(175 ,304,1),
                                                 MakePoint(177 ,311,1),
                                                 MakePoint(179 ,319,1),
                                                 MakePoint(182 ,328,1),
                                                 MakePoint(186 ,339,1),
                                                 MakePoint(190 ,349,1),
                                                 MakePoint(194 ,361,1),
                                                 MakePoint(199 ,372,1),
                                                 MakePoint(204 ,386,1),
                                                 MakePoint(210 ,400,1),
                                                 MakePoint(215 ,414,1),
                                                 MakePoint(221 ,428,1),
                                                 MakePoint(227 ,443,1),
                                                 MakePoint(232 ,457,1),
                                                 MakePoint(238 ,472,1),
                                                 MakePoint(244 ,487,1),
                                                 MakePoint(249 ,501,1),
                                                 MakePoint(254 ,516,1),
                                                 MakePoint(259 ,529,1),
                                                 MakePoint(263 ,540,1),
                                                 MakePoint(267 ,552,1),
                                                 MakePoint(271 ,564,1),
                                                 MakePoint(274 ,576,1),
                                                 MakePoint(278 ,587,1),
                                                 MakePoint(281 ,599,1),
                                                 MakePoint(286 ,611,1),
                                                 MakePoint(291 ,625,1),
                                                 MakePoint(296 ,635,1),
                                                 MakePoint(300 ,647,1),
                                                 MakePoint(305 ,658,1),
                                                 MakePoint(309 ,670,1),
                                                 MakePoint(313 ,682,1),
                                                 MakePoint(318 ,694,1),
                                                 MakePoint(322 ,706,1),
                                                 MakePoint(326 ,717,1),
                                                 MakePoint(330 ,727,1),
                                                 MakePoint(333 ,735,1),
                                                 MakePoint(336 ,743,1),
                                                 MakePoint(338 ,750,1),
                                                 MakePoint(340 ,755,1),
                                                 MakePoint(342 ,758,1),
                                                 MakePoint(344 ,760,1),
                                                 MakePoint(345 ,761,1),
                                                 MakePoint(346 ,762,1),
                                                 MakePoint(347 ,762,1),
                                                 MakePoint(349 ,762,1),
                                                 MakePoint(352 ,758,1),
                                                 MakePoint(358 ,751,1),
                                                 MakePoint(365 ,743,1),
                                                 MakePoint(374 ,731,1),
                                                 MakePoint(383 ,719,1),
                                                 MakePoint(394 ,704,1),
                                                 MakePoint(403 ,690,1),
                                                 MakePoint(412 ,673,1),
                                                 MakePoint(419 ,657,1),
                                                 MakePoint(427 ,639,1),
                                                 MakePoint(435 ,617,1),
                                                 MakePoint(443 ,597,1),
                                                 MakePoint(451 ,576,1),
                                                 MakePoint(457 ,555,1),
                                                 MakePoint(463 ,534,1),
                                                 MakePoint(469 ,512,1),
                                                 MakePoint(474 ,494,1),
                                                 MakePoint(479 ,476,1),
                                                 MakePoint(484 ,457,1),
                                                 MakePoint(488 ,439,1),
                                                 MakePoint(493 ,422,1),
                                                 MakePoint(499 ,405,1),
                                                 MakePoint(504 ,389,1),
                                                 MakePoint(509 ,377,1),
                                                 MakePoint(513 ,366,1),
                                                 MakePoint(517 ,355,1),
                                                 MakePoint(521 ,346,1),
                                                 MakePoint(524 ,338,1),
                                                 MakePoint(527 ,331,1),
                                                 MakePoint(529 ,325,1),
                                                 MakePoint(531 ,318,1),
                                                 MakePoint(533 ,312,1),
                                                 MakePoint(535 ,306,1),
                                                 MakePoint(536 ,302,1),
                                                 MakePoint(537 ,297,1),
                                                 MakePoint(538 ,293,1),
                                                 MakePoint(540 ,288,1),
                                                 MakePoint(541 ,284,1),
                                                 MakePoint(542 ,280,1),
                                                 MakePoint(543 ,277,1),
                                                 MakePoint(544 ,273,1),
                                                 MakePoint(545 ,270,1),
                                                 MakePoint(545 ,267,1),
                                                 MakePoint(546 ,265,1),
                                                 MakePoint(547 ,262,1),
                                                 MakePoint(548 ,259,1),
                                                 MakePoint(548 ,257,1),
                                                 MakePoint(549 ,256,1),
                                                 MakePoint(549 ,255,1),
                                                 MakePoint(550 ,254,1),
                                                 MakePoint(550 ,253,1),
                                                 MakePoint(550 ,252,1)
                                         ]);
    	pointClouds[10] = MakePointCloud(@"null", @[
                                         MakePoint(382,310,1),
                                         MakePoint(377,308,1),
                                         MakePoint(373,307,1),
                                         MakePoint(366,307,1),
                                         MakePoint(360,310,1),
                                         MakePoint(356,313,1),
                                         MakePoint(353,316,1),
                                         MakePoint(349,321,1),
                                         MakePoint(347,326,1),
                                         MakePoint(344,331,1),
                                         MakePoint(342,337,1),
                                         MakePoint(341,343,1),
                                         MakePoint(341,350,1),
                                         MakePoint(341,358,1),
                                         MakePoint(342,362,1),
                                         MakePoint(344,366,1),
                                         MakePoint(347,370,1),
                                         MakePoint(351,374,1),
                                         MakePoint(356,379,1),
                                         MakePoint(361,382,1),
                                         MakePoint(368,385,1),
                                         MakePoint(374,387,1),
                                         MakePoint(381,387,1),
                                         MakePoint(390,387,1),
                                         MakePoint(397,385,1),
                                         MakePoint(404,382,1),
                                         MakePoint(408,378,1),
                                         MakePoint(412,373,1),
                                         MakePoint(416,367,1),
                                         MakePoint(418,361,1),
                                         MakePoint(419,353,1),
                                         MakePoint(418,346,1),
                                         MakePoint(417,341,1),
                                         MakePoint(416,336,1),
                                         MakePoint(413,331,1),
                                         MakePoint(410,326,1),
                                         MakePoint(404,320,1),
                                         MakePoint(400,317,1),
                                         MakePoint(393,313,1),
                                         MakePoint(392,312,1),
    
                                         MakePoint(418,309,2),
                                         MakePoint(337,390,2)
                                        ]);
    	pointClouds[11] = MakePointCloud(@"A", @[
                                                 MakePoint(172 ,777,1),
                                                 MakePoint(172 ,771,1),
                                                 MakePoint(175 ,761,1),
                                                 MakePoint(179 ,745,1),
                                                 MakePoint(185 ,726,1),
                                                 MakePoint(194 ,700,1),
                                                 MakePoint(203 ,672,1),
                                                 MakePoint(212 ,642,1),
                                                 MakePoint(221 ,614,1),
                                                 MakePoint(232 ,582,1),
                                                 MakePoint(244 ,543,1),
                                                 MakePoint(255 ,507,1),
                                                 MakePoint(266 ,471,1),
                                                 MakePoint(276 ,437,1),
                                                 MakePoint(285 ,406,1),
                                                 MakePoint(294 ,376,1),
                                                 MakePoint(308 ,328,1),
                                                 MakePoint(319 ,291,1),
                                                 MakePoint(326 ,267,1),
                                                 MakePoint(332 ,245,1),
                                                 MakePoint(336 ,228,1),
                                                 MakePoint(340 ,216,1),
                                                 MakePoint(342 ,204,1),
                                                 MakePoint(345 ,196,1),
                                                 MakePoint(347 ,189,1),
                                                 MakePoint(349 ,183,1),
                                                 MakePoint(350 ,178,1),
                                                 MakePoint(351 ,175,1),
                                                 MakePoint(353 ,174,1),
                                                 MakePoint(354 ,174,1),
                                                 MakePoint(356 ,174,1),
                                                 MakePoint(357 ,177,1),
                                                 MakePoint(360 ,185,1),
                                                 MakePoint(365 ,200,1),
                                                 MakePoint(372 ,222,1),
                                                 MakePoint(380 ,248,1),
                                                 MakePoint(390 ,278,1),
                                                 MakePoint(400 ,313,1),
                                                 MakePoint(412 ,347,1),
                                                 MakePoint(425 ,383,1),
                                                 MakePoint(438 ,423,1),
                                                 MakePoint(452 ,462,1),
                                                 MakePoint(465 ,503,1),
                                                 MakePoint(477 ,544,1),
                                                 MakePoint(487 ,581,1),
                                                 MakePoint(496 ,619,1),
                                                 MakePoint(504 ,655,1),
                                                 MakePoint(511 ,687,1),
                                                 MakePoint(517 ,714,1),
                                                 MakePoint(521 ,733,1),
                                                 MakePoint(525 ,749,1),
                                                 MakePoint(527 ,760,1),
                                                 MakePoint(529 ,768,1),
                                                 MakePoint(530 ,773,1),
                                                 MakePoint(530 ,776,1),
                                                 MakePoint(530 ,777,1),
                                                 MakePoint(529 ,775,1),
                                                 MakePoint(242 ,473,2),
                                                 MakePoint(251 ,473,2),
                                                 MakePoint(266 ,473,2),
                                                 MakePoint(286 ,472,2),
                                                 MakePoint(308 ,471,2),
                                                 MakePoint(333 ,470,2),
                                                 MakePoint(363 ,470,2),
                                                 MakePoint(385 ,469,2),
                                                 MakePoint(407 ,469,2),
                                                 MakePoint(425 ,469,2),
                                                 MakePoint(438 ,469,2),
                                                 MakePoint(448 ,469,2),
                                                 MakePoint(456 ,469,2),
                                                 MakePoint(461 ,469,2),
                                                 MakePoint(465 ,469,2),
                                                 MakePoint(466 ,469,2),
                                                 MakePoint(468 ,469,2),
                                                 MakePoint(469 ,469,2),
                                                 MakePoint(470 ,469,2),
                                                 MakePoint(471 ,469,2),
                                                 MakePoint(472 ,469,2),
                                                 MakePoint(474 ,469,2),
                                                 MakePoint(475 ,469,2),
                                                 MakePoint(476 ,469,2),
                                                 MakePoint(478 ,469,2),
                                                 MakePoint(480 ,469,2),
                                                 MakePoint(482 ,469,2),
                                                 MakePoint(484 ,469,2),
                                                 MakePoint(485 ,469,2),
                                                 MakePoint(487 ,469,2),
                                                 MakePoint(487 ,469,2)
                                         ]);
    	pointClouds[12] = MakePointCloud(@"I", @[
                                                 MakePoint(163 ,254,1),
                                                 MakePoint(172 ,255,1),
                                                 MakePoint(190 ,257,1),
                                                 MakePoint(213 ,257,1),
                                                 MakePoint(245 ,257,1),
                                                 MakePoint(279 ,257,1),
                                                 MakePoint(317 ,256,1),
                                                 MakePoint(357 ,252,1),
                                                 MakePoint(398 ,249,1),
                                                 MakePoint(436 ,246,1),
                                                 MakePoint(471 ,244,1),
                                                 MakePoint(502 ,241,1),
                                                 MakePoint(527 ,239,1),
                                                 MakePoint(544 ,238,1),
                                                 MakePoint(557 ,236,1),
                                                 MakePoint(565 ,235,1),
                                                 MakePoint(569 ,234,1),
                                                 MakePoint(570 ,234,1),
                                                 MakePoint(353 ,261,2),
                                                 MakePoint(353 ,264,2),
                                                 MakePoint(353 ,268,2),
                                                 MakePoint(353 ,276,2),
                                                 MakePoint(353 ,287,2),
                                                 MakePoint(351 ,301,2),
                                                 MakePoint(350 ,323,2),
                                                 MakePoint(350 ,346,2),
                                                 MakePoint(350 ,375,2),
                                                 MakePoint(350 ,404,2),
                                                 MakePoint(351 ,433,2),
                                                 MakePoint(352 ,461,2),
                                                 MakePoint(352 ,492,2),
                                                 MakePoint(352 ,524,2),
                                                 MakePoint(352 ,552,2),
                                                 MakePoint(352 ,579,2),
                                                 MakePoint(352 ,602,2),
                                                 MakePoint(352 ,624,2),
                                                 MakePoint(352 ,644,2),
                                                 MakePoint(353 ,660,2),
                                                 MakePoint(354 ,676,2),
                                                 MakePoint(355 ,690,2),
                                                 MakePoint(355 ,703,2),
                                                 MakePoint(356 ,713,2),
                                                 MakePoint(356 ,722,2),
                                                 MakePoint(356 ,729,2),
                                                 MakePoint(357 ,734,2),
                                                 MakePoint(357 ,737,2),
                                                 MakePoint(357 ,740,2),
                                                 MakePoint(357 ,741,2),
                                                 MakePoint(356 ,741,2),
                                                 MakePoint(351 ,742,2),
                                                 MakePoint(343 ,742,2),
                                                 MakePoint(330 ,742,2),
                                                 MakePoint(312 ,742,2),
                                                 MakePoint(289 ,742,2),
                                                 MakePoint(261 ,742,2),
                                                 MakePoint(234 ,743,2),
                                                 MakePoint(206 ,746,2),
                                                 MakePoint(184 ,748,2),
                                                 MakePoint(163 ,750,2),
                                                 MakePoint(144 ,751,2),
                                                 MakePoint(132 ,753,2),
                                                 MakePoint(123 ,753,2),
                                                 MakePoint(117 ,753,2),
                                                 MakePoint(114 ,753,2),
                                                 MakePoint(113 ,753,2),
                                                 MakePoint(114 ,753,2),
                                                 MakePoint(124 ,753,2),
                                                 MakePoint(142 ,753,2),
                                                 MakePoint(165 ,753,2),
                                                 MakePoint(196 ,753,2),
                                                 MakePoint(230 ,753,2),
                                                 MakePoint(268 ,753,2),
                                                 MakePoint(307 ,753,2),
                                                 MakePoint(350 ,753,2),
                                                 MakePoint(393 ,753,2),
                                                 MakePoint(432 ,753,2),
                                                 MakePoint(469 ,753,2),
                                                 MakePoint(502 ,755,2),
                                                 MakePoint(530 ,756,2),
                                                 MakePoint(550 ,756,2),
                                                 MakePoint(571 ,756,2),
                                                 MakePoint(590 ,757,2),
                                                 MakePoint(607 ,757,2),
                                                 MakePoint(621 ,757,2),
                                                 MakePoint(635 ,756,2),
                                                 MakePoint(645 ,754,2),
                                                 MakePoint(652 ,753,2),
                                                 MakePoint(656 ,751,2),
                                                 MakePoint(659 ,750,2),
                                                 MakePoint(659 ,750,2),
                                                 MakePoint(659 ,749,2),
                                                 MakePoint(657 ,749,2)
                                         ]);
    	pointClouds[13] = MakePointCloud(@"E", @[
                                                 MakePoint(515 ,237,1),
                                                 MakePoint(506 ,235,1),
                                                 MakePoint(491 ,230,1),
                                                 MakePoint(470 ,225,1),
                                                 MakePoint(449 ,219,1),
                                                 MakePoint(422 ,216,1),
                                                 MakePoint(392 ,214,1),
                                                 MakePoint(358 ,214,1),
                                                 MakePoint(326 ,215,1),
                                                 MakePoint(301 ,218,1),
                                                 MakePoint(277 ,223,1),
                                                 MakePoint(257 ,227,1),
                                                 MakePoint(243 ,230,1),
                                                 MakePoint(231 ,233,1),
                                                 MakePoint(222 ,238,1),
                                                 MakePoint(217 ,245,1),
                                                 MakePoint(215 ,254,1),
                                                 MakePoint(215 ,271,1),
                                                 MakePoint(216 ,292,1),
                                                 MakePoint(220 ,318,1),
                                                 MakePoint(223 ,352,1),
                                                 MakePoint(225 ,388,1),
                                                 MakePoint(226 ,425,1),
                                                 MakePoint(226 ,465,1),
                                                 MakePoint(226 ,506,1),
                                                 MakePoint(225 ,542,1),
                                                 MakePoint(222 ,575,1),
                                                 MakePoint(218 ,607,1),
                                                 MakePoint(214 ,638,1),
                                                 MakePoint(212 ,661,1),
                                                 MakePoint(209 ,684,1),
                                                 MakePoint(207 ,704,1),
                                                 MakePoint(205 ,718,1),
                                                 MakePoint(204 ,730,1),
                                                 MakePoint(203 ,739,1),
                                                 MakePoint(202 ,745,1),
                                                 MakePoint(202 ,749,1),
                                                 MakePoint(202 ,751,1),
                                                 MakePoint(202 ,752,1),
                                                 MakePoint(202 ,753,1),
                                                 MakePoint(205 ,753,1),
                                                 MakePoint(217 ,752,1),
                                                 MakePoint(236 ,748,1),
                                                 MakePoint(259 ,741,1),
                                                 MakePoint(293 ,734,1),
                                                 MakePoint(328 ,726,1),
                                                 MakePoint(365 ,718,1),
                                                 MakePoint(401 ,712,1),
                                                 MakePoint(433 ,705,1),
                                                 MakePoint(461 ,698,1),
                                                 MakePoint(482 ,692,1),
                                                 MakePoint(500 ,685,1),
                                                 MakePoint(513 ,681,1),
                                                 MakePoint(523 ,676,1),
                                                 MakePoint(529 ,673,1),
                                                 MakePoint(533 ,672,1),
                                                 MakePoint(534 ,671,1),
                                                 MakePoint(250 ,474,2),
                                                 MakePoint(257 ,473,2),
                                                 MakePoint(270 ,471,2),
                                                 MakePoint(289 ,468,2),
                                                 MakePoint(311 ,463,2),
                                                 MakePoint(342 ,458,2),
                                                 MakePoint(373 ,452,2),
                                                 MakePoint(404 ,446,2),
                                                 MakePoint(433 ,440,2),
                                                 MakePoint(457 ,435,2),
                                                 MakePoint(479 ,430,2),
                                                 MakePoint(495 ,426,2),
                                                 MakePoint(504 ,423,2),
                                                 MakePoint(509 ,422,2),
                                                 MakePoint(511 ,421,2),
                                                 MakePoint(511 ,419,2)                                       ]);
    
  
    	pointClouds[14] = MakePointCloud(@"f", @[
                                                       MakePoint(405 ,143,1),
                                                       MakePoint(401 ,140,1),
                                                       MakePoint(393 ,136,1),
                                                       MakePoint(386 ,132,1),
                                                       MakePoint(377 ,126,1),
                                                       MakePoint(367 ,123,1),
                                                       MakePoint(356 ,121,1),
                                                       MakePoint(342 ,121,1),
                                                       MakePoint(326 ,121,1),
                                                       MakePoint(312 ,122,1),
                                                       MakePoint(301 ,127,1),
                                                       MakePoint(291 ,135,1),
                                                       MakePoint(284 ,144,1),
                                                       MakePoint(278 ,154,1),
                                                       MakePoint(273 ,168,1),
                                                       MakePoint(267 ,187,1),
                                                       MakePoint(265 ,208,1),
                                                       MakePoint(264 ,233,1),
                                                       MakePoint(263 ,259,1),
                                                       MakePoint(263 ,290,1),
                                                       MakePoint(262 ,327,1),
                                                       MakePoint(262 ,364,1),
                                                       MakePoint(262 ,401,1),
                                                       MakePoint(262 ,441,1),
                                                       MakePoint(262 ,482,1),
                                                       MakePoint(262 ,523,1),
                                                       MakePoint(262 ,565,1),
                                                       MakePoint(263 ,607,1),
                                                       MakePoint(265 ,642,1),
                                                       MakePoint(267 ,666,1),
                                                       MakePoint(268 ,685,1),
                                                       MakePoint(269 ,696,1),
                                                       MakePoint(270 ,703,1),
                                                       MakePoint(270 ,706,1),
                                                       MakePoint(270 ,707,1),
                                                       MakePoint(173 ,399,2),
                                                       MakePoint(180 ,399,2),
                                                       MakePoint(194 ,399,2),
                                                       MakePoint(214 ,396,2),
                                                       MakePoint(236 ,394,2),
                                                       MakePoint(258 ,392,2),
                                                       MakePoint(284 ,390,2),
                                                       MakePoint(309 ,389,2),
                                                       MakePoint(333 ,388,2),
                                                       MakePoint(350 ,387,2),
                                                       MakePoint(363 ,385,2),
                                                       MakePoint(372 ,385,2),
                                                       MakePoint(377 ,384,2),
                                                       MakePoint(380 ,384,2),
                                                       MakePoint(381 ,384,2),
                                                       MakePoint(382 ,384,2),
                                                       MakePoint(378 ,384,2)
                                         ]);
    	pointClouds[15] = MakePointCloud(@"L", @[
                                                 MakePoint(156 ,181,1),
                                                 MakePoint(156 ,187,1),
                                                 MakePoint(156 ,199,1),
                                                 MakePoint(156 ,215,1),
                                                 MakePoint(156 ,237,1),
                                                 MakePoint(158 ,260,1),
                                                 MakePoint(161 ,286,1),
                                                 MakePoint(163 ,314,1),
                                                 MakePoint(165 ,343,1),
                                                 MakePoint(167 ,373,1),
                                                 MakePoint(168 ,403,1),
                                                 MakePoint(168 ,432,1),
                                                 MakePoint(168 ,460,1),
                                                 MakePoint(168 ,485,1),
                                                 MakePoint(168 ,510,1),
                                                 MakePoint(168 ,533,1),
                                                 MakePoint(169 ,551,1),
                                                 MakePoint(170 ,569,1),
                                                 MakePoint(171 ,581,1),
                                                 MakePoint(172 ,596,1),
                                                 MakePoint(172 ,607,1),
                                                 MakePoint(172 ,616,1),
                                                 MakePoint(172 ,624,1),
                                                 MakePoint(172 ,630,1),
                                                 MakePoint(172 ,636,1),
                                                 MakePoint(172 ,640,1),
                                                 MakePoint(172 ,643,1),
                                                 MakePoint(172 ,644,1),
                                                 MakePoint(172 ,645,1),
                                                 MakePoint(172 ,646,1),
                                                 MakePoint(173 ,646,1),
                                                 MakePoint(175 ,646,1),
                                                 MakePoint(180 ,646,1),
                                                 MakePoint(192 ,647,1),
                                                 MakePoint(209 ,647,1),
                                                 MakePoint(233 ,648,1),
                                                 MakePoint(258 ,648,1),
                                                 MakePoint(286 ,648,1),
                                                 MakePoint(317 ,648,1),
                                                 MakePoint(354 ,647,1),
                                                 MakePoint(391 ,645,1),
                                                 MakePoint(429 ,642,1),
                                                 MakePoint(464 ,640,1),
                                                 MakePoint(497 ,638,1),
                                                 MakePoint(523 ,638,1),
                                                 MakePoint(542 ,638,1),
                                                 MakePoint(556 ,638,1),
                                                 MakePoint(566 ,638,1),
                                                 MakePoint(570 ,638,1),
                                                 MakePoint(572 ,638,1),
                                                 MakePoint(573 ,638,1),
                                                 MakePoint(572 ,638,1),
                                                 MakePoint(571 ,638,1),
                                                 MakePoint(570 ,638,1)
                                        ]);
    
    	    	pointClouds[15] = MakePointCloud(@"P", @[
                                                         MakePoint(237 ,240,1),
                                                         MakePoint(237 ,254,1),
                                                         MakePoint(237 ,280,1),
                                                         MakePoint(237 ,308,1),
                                                         MakePoint(237 ,348,1),
                                                         MakePoint(237 ,389,1),
                                                         MakePoint(236 ,431,1),
                                                         MakePoint(235 ,476,1),
                                                         MakePoint(234 ,520,1),
                                                         MakePoint(234 ,568,1),
                                                         MakePoint(234 ,614,1),
                                                         MakePoint(235 ,661,1),
                                                         MakePoint(236 ,705,1),
                                                         MakePoint(236 ,744,1),
                                                         MakePoint(236 ,779,1),
                                                         MakePoint(224 ,234,2),
                                                         MakePoint(227 ,232,2),
                                                         MakePoint(239 ,228,2),
                                                         MakePoint(259 ,220,2),
                                                         MakePoint(283 ,212,2),
                                                         MakePoint(308 ,206,2),
                                                         MakePoint(340 ,200,2),
                                                         MakePoint(367 ,197,2),
                                                         MakePoint(394 ,197,2),
                                                         MakePoint(425 ,200,2),
                                                         MakePoint(452 ,209,2),
                                                         MakePoint(476 ,223,2),
                                                         MakePoint(497 ,237,2),
                                                         MakePoint(511 ,250,2),
                                                         MakePoint(525 ,266,2),
                                                         MakePoint(534 ,284,2),
                                                         MakePoint(539 ,303,2),
                                                         MakePoint(539 ,321,2),
                                                         MakePoint(536 ,344,2),
                                                         MakePoint(524 ,369,2),
                                                         MakePoint(510 ,386,2),
                                                         MakePoint(490 ,406,2),
                                                         MakePoint(468 ,421,2),
                                                         MakePoint(443 ,436,2),
                                                         MakePoint(414 ,450,2),
                                                         MakePoint(385 ,461,2),
                                                         MakePoint(359 ,470,2),
                                                         MakePoint(336 ,476,2),
                                                         MakePoint(312 ,481,2),
                                                         MakePoint(292 ,483,2),
                                                         MakePoint(277 ,485,2),
                                                         MakePoint(264 ,486,2),
                                                         MakePoint(254 ,487,2),
                                                         MakePoint(246 ,487,2),
                                                         MakePoint(240 ,488,2),
                                                         MakePoint(233 ,489,2)
                                         ]);
    
    	pointClouds[16] = MakePointCloud(@"L", @[
                                                 MakePoint(201 ,167,1),
                                                 MakePoint(201 ,183,1),
                                                 MakePoint(201 ,212,1),
                                                 MakePoint(201 ,251,1),
                                                 MakePoint(201 ,290,1),
                                                 MakePoint(199 ,334,1),
                                                 MakePoint(196 ,382,1),
                                                 MakePoint(193 ,432,1),
                                                 MakePoint(191 ,486,1),
                                                 MakePoint(190 ,540,1),
                                                 MakePoint(187 ,592,1),
                                                 MakePoint(185 ,641,1),
                                                 MakePoint(182 ,683,1),
                                                 MakePoint(180 ,715,1),
                                                 MakePoint(180 ,739,1),
                                                 MakePoint(180 ,756,1),
                                                 MakePoint(180 ,767,1),
                                                 MakePoint(181 ,775,1),
                                                 MakePoint(186 ,779,1),
                                                 MakePoint(199 ,781,1),
                                                 MakePoint(219 ,782,1),
                                                 MakePoint(251 ,782,1),
                                                 MakePoint(292 ,781,1),
                                                 MakePoint(339 ,779,1),
                                                 MakePoint(391 ,778,1),
                                                 MakePoint(445 ,778,1),
                                                 MakePoint(494 ,778,1),
                                                 MakePoint(536 ,778,1),
                                                 MakePoint(571 ,778,1),
                                                 MakePoint(602 ,778,1),
                                                 MakePoint(626 ,776,1),
                                                 MakePoint(641 ,773,1),
                                                 MakePoint(649 ,772,1),
                                                 MakePoint(652 ,771,1),
                                                 MakePoint(653 ,770,1)
                                        ]);
    
    //	pointClouds[13] = MakePointCloud(@"six-point star", @[
    //                                     MakePoint(177,554,1),
    //                                     MakePoint(223,476,1),
    //                                     MakePoint(268,554,1),
    //                                     MakePoint(183,554,1),
    //
    //                                     MakePoint(177,490,2),
    //                                     MakePoint(223,568,2),
    //                                     MakePoint(268,490,2),
    //                                     MakePoint(183,490,2)
    //                                    ]);
    
    //	pointClouds[14] = MakePointCloud(@"asterisk", @[
    //                                     MakePoint(325,499,1),
    //                                     MakePoint(417,557,1),
    //
    //                                     MakePoint(417,499,2),
    //                                     MakePoint(325,557,2),
    //
    //                                     MakePoint(371,486,3),
    //                                     MakePoint(371,571,3)
    //                                    ]);
    
    //	pointClouds[15] = MakePointCloud(@"half-note", @[
    //                                     MakePoint(546,465,1),
    //                                     MakePoint(546,531,1),
    //
    //                                     MakePoint(540,530,2),
    //                                     MakePoint(536,529,2),
    //                                     MakePoint(533,528,2),
    //                                     MakePoint(529,529,2),
    //                                     MakePoint(524,530,2),
    //                                     MakePoint(520,532,2),
    //                                     MakePoint(515,535,2),
    //                                     MakePoint(511,539,2),
    //                                     MakePoint(508,545,2),
    //                                     MakePoint(506,548,2),
    //                                     MakePoint(506,554,2),
    //                                     MakePoint(509,558,2),
    //                                     MakePoint(512,561,2),
    //                                     MakePoint(517,564,2),
    //                                     MakePoint(521,564,2),
    //                                     MakePoint(527,563,2),
    //                                     MakePoint(531,560,2),
    //                                     MakePoint(535,557,2),
    //                                     MakePoint(538,553,2),
    //                                     MakePoint(542,548,2),
    //                                     MakePoint(544,544,2),
    //                                     MakePoint(546,540,2),
    //                                     MakePoint(546,536,2)
    //                                    ]);
    
    
    return pointClouds;
}

@end



